import { Inter } from "next/font/google";
import "./globals.css";
import AuthProvider from "./provider/AuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Dash",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <AuthProvider>
        <body className={inter.className}>
          <div className="home_top">
            <div className="child_section">{children}</div>
          </div>
        </body>
      </AuthProvider>
    </html>
  );
}
